-- Moins Commun v4
-- À exécuter dans Supabase SQL Editor

create extension if not exists "pgcrypto";

drop view if exists public.song_details;
drop table if exists public.song_relationships cascade;
drop table if exists public.song_submissions cascade;
drop table if exists public.favorites cascade;
drop table if exists public.songs cascade;
drop table if exists public.artists cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.artists (
  id bigint generated by default as identity primary key,
  name text not null unique,
  country text,
  bio text,
  created_at timestamptz not null default now()
);

create table public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist_id bigint references public.artists(id) on delete set null,
  release_year integer,
  genre text,
  description text,
  cover_url text,
  status text not null default 'published' check (status in ('draft','published')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.song_relationships (
  id bigint generated by default as identity primary key,
  primary_song_id bigint not null references public.songs(id) on delete cascade,
  related_song_id bigint not null references public.songs(id) on delete cascade,
  relation_type text not null check (
    relation_type in (
      'sampled','sampled_by',
      'cover_of','covered_by',
      'remix_of','remixed_by',
      'interpolation_of','interpolated_by'
    )
  ),
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  check (primary_song_id <> related_song_id)
);

create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, song_id)
);

create table public.song_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  artist_id bigint references public.artists(id) on delete set null,
  artist_name_text text,
  release_year integer,
  genre text,
  description text,
  cover_url text,
  relation_type text check (
    relation_type in (
      'sampled','sampled_by',
      'cover_of','covered_by',
      'remix_of','remixed_by',
      'interpolation_of','interpolated_by'
    )
  ),
  related_song_id bigint references public.songs(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  approved_song_id bigint references public.songs(id) on delete set null,
  reviewed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(check_user uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = check_user), false);
$$;

create view public.song_details as
select
  s.id,
  s.title,
  s.release_year,
  s.genre,
  s.description,
  s.cover_url,
  s.status,
  s.created_at,
  a.id as artist_id,
  a.name as artist_name
from public.songs s
left join public.artists a on a.id = s.artist_id;

alter table public.profiles enable row level security;
alter table public.artists enable row level security;
alter table public.songs enable row level security;
alter table public.song_relationships enable row level security;
alter table public.favorites enable row level security;
alter table public.song_submissions enable row level security;

create policy "profiles readable by everyone"
on public.profiles for select
to authenticated, anon
using (true);

create policy "profiles users can update themselves"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "artists readable by everyone"
on public.artists for select
to authenticated, anon
using (true);

create policy "artists admins can write"
on public.artists for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "songs published readable by everyone"
on public.songs for select
to authenticated, anon
using (status = 'published' or public.is_admin(auth.uid()));

create policy "songs admins can write"
on public.songs for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "relationships readable by everyone"
on public.song_relationships for select
to authenticated, anon
using (
  exists (
    select 1 from public.songs s
    where s.id = primary_song_id
    and (s.status = 'published' or public.is_admin(auth.uid()))
  )
);

create policy "relationships admins can write"
on public.song_relationships for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "favorites user can read own"
on public.favorites for select
to authenticated
using (auth.uid() = user_id);

create policy "favorites user can insert own"
on public.favorites for insert
to authenticated
with check (auth.uid() = user_id);

create policy "favorites user can delete own"
on public.favorites for delete
to authenticated
using (auth.uid() = user_id);

create policy "submissions users can read own or admins"
on public.song_submissions for select
to authenticated
using (auth.uid() = user_id or public.is_admin(auth.uid()));

create policy "submissions authenticated can insert own"
on public.song_submissions for insert
to authenticated
with check (auth.uid() = user_id);

create policy "submissions admins can update"
on public.song_submissions for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

insert into public.artists (name, country, bio) values
  ('Kanye West', 'USA', 'Producteur et rappeur au cœur de nombreuses connexions musicales.'),
  ('Daft Punk', 'France', 'Duo électronique iconique.'),
  ('Coolio', 'USA', 'Rappeur américain connu pour Gangsta''s Paradise.'),
  ('Stevie Wonder', 'USA', 'Auteur-compositeur majeur de la soul et du funk.')
on conflict (name) do nothing;

insert into public.songs (title, artist_id, release_year, genre, description, status) values
  ('Stronger', (select id from public.artists where name = 'Kanye West'), 2007, 'Hip-Hop', 'Titre contenant un sample très connu de Daft Punk.', 'published'),
  ('Harder, Better, Faster, Stronger', (select id from public.artists where name = 'Daft Punk'), 2001, 'Electronic', 'Classique électronique samplé par Kanye West.', 'published'),
  ('Gangsta''s Paradise', (select id from public.artists where name = 'Coolio'), 1995, 'Hip-Hop', 'Hit de Coolio inspiré d''un morceau de Stevie Wonder.', 'published'),
  ('Pastime Paradise', (select id from public.artists where name = 'Stevie Wonder'), 1976, 'Soul', 'Morceau culte servant de base à Gangsta''s Paradise.', 'published');

insert into public.song_relationships (primary_song_id, related_song_id, relation_type, notes)
values
  ((select id from public.songs where title = 'Stronger'), (select id from public.songs where title = 'Harder, Better, Faster, Stronger'), 'sampled', 'Sample principal du refrain.'),
  ((select id from public.songs where title = 'Gangsta''s Paradise'), (select id from public.songs where title = 'Pastime Paradise'), 'sampled', 'Réinterprétation / adaptation autour du motif original.');

grant usage on schema public to anon, authenticated;
grant select on public.song_details to anon, authenticated;
